export interface product{
    id:number,
    title:string,
    description:string,
    price:number,
    thumbnail:string,
    images:[],
    stock:number,
    brand:string,
    weight:number,
    dimensions:{
        width:number,
        height:number,
        depth:number,
    }
    rating:number,
    reviews:[{
        rating:number,
        comment:string,
        date:string,
        reviewerName:string,
        reviewerEmail:string,
    }],
    warrantyInformation:string,
    shippingInformation:string,
    availabilityStatus:string,
}